#!/bin/bash -l
#PBS -l walltime=24:00:00,nodes=1:ppn=24,mem=32gb

source ~/.bashrc
cd /home/yangyh/lixx3899/kaggle-yelp/model
python level3_model.py --yix 0
python level3_model.py --yix 1
python level3_model.py --yix 2
python level3_model.py --yix 3
python level3_model.py --yix 4
python level3_model.py --yix 5
python level3_model.py --yix 6
python level3_model.py --yix 7
python level3_model.py --yix 8
