#!/bin/bash -l
#PBS -l walltime=24:00:00,nodes=1:ppn=24,mem=32gb

source ~/.bashrc
cd /home/yangyh/lixx3899/kaggle-yelp/model
python pic_level_ftr.py --yix 0
# python level4_data.py --yix 1
# python level4_data.py --yix 2
# python level4_data.py --yix 3
# python level4_data.py --yix 4
# python level4_data.py --yix 5
# python level4_data.py --yix 6
# python level4_data.py --yix 7
# python level4_data.py --yix 8
